name: Trigger Prototype Workflow by Comment

on:
  issue_comment:                                     
    types: [created]

jobs:
  trigger_prototype_workflow_by_comment:
    name: Trigger Prototype Workflow by Comment
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/build') }} 
    runs-on: ubuntu-latest
    env:
      CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: 'get-branch'
        run: |
          echo "GITHUB_BRANCH=$(gh pr view $PR_NO --repo $REPO --json headRefName --jq '.headRefName')" >> $GITHUB_ENV
          echo ::set-output name=branch::$(gh pr view $PR_NO --repo $REPO --json headRefName --jq '.headRefName')
        env:
          REPO: ${{ github.repository }}
          PR_NO: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger3
        run: |
          echo ${{ env.GITHUB_BRANCH }}
          echo ${{ steps.get-branch.outputs.branch }}
          echo ${{ github.event.issue_comment.author }}
