name: Trigger Prototype Workflow by Comment

on:
  issue_comment:                                     
    types: [created]

jobs:
  trigger_prototype_workflow_by_comment:
    name: Trigger Prototype Workflow by Comment
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/build') }} 
    runs-on: ubuntu-latest
    env:
      CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
    steps:
      - name: Trigger Prototype Workflow 
        run: |
          echo ${GITHUB_REF#refs/heads/}
