name: Trigger Prototype Workflow by Comment

on:
  push

jobs:
  trigger_prototype_workflow_by_comment:
    name: Trigger Prototype Workflow by Comment
    if: ${{ github.event.issue.pull_request }} && contains(github.event.comment.body, '/build_prototype_app')
    runs-on: ubuntu-latest
    env:
      CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Trigger Prototype Workflow 
        run: |
          echo "ASU ECHO2"
