name: Trigger Prototype Workflow by Comment

on:
  issue_comment:                                     
    types: [created]

jobs:
  trigger_prototype_workflow_by_comment:
    name: Trigger Prototype Workflow by Comment
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/build') }} 
    runs-on: ubuntu-latest
    env:
      CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Checkout Pull Request
        run: |
          hub pr checkout ${{ github.event.issue.number }}
          echo ${GITHUB_REF#refs/heads/}
      - name: Trigger
        run: echo ${GITHUB_REF#refs/heads/}
      - name: Get the current branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: myref
      - name: Trigger
        run: echo ${{ steps.myref.outputs.branch }}
