name: Milestoned

on:
  pull_request:
    types: [milestoned]

jobs:
    milestoned:
        runs-on: ubuntu-latest
        steps:
        - name: Update milestone on PRs targeting this version
          uses: actions/github-script@v7
          with:
            script: |
              let milestone = '${{ github.event.pull_request.milestone.title }}'.slice(0, -1) + "0"
              const release_issue_regex = /\[([0-9\.]*)\]/
              let release_issues = await github.rest.issues.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: "release-automation",
                state: "open"
              })
              console.log(release_issues)
              let release_issues_version = release_issues.data.map ((release_issue) => {
                return release_issue.title.match(release_issue_regex)[1]
              })
              console.log(release_issues_version)

              if (release_issues_version.includes(milestone)) {
                console.log("Milestone is set to QA versions")
                await github.rest.pulls.requestReviewers({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: ${{ github.event.pull_request.number }},
                  reviewers: "RzRnt"
                });
              } else {
                console.log("Milestone is set to non QA versions!")
              }
