name: Milestoned

on:
  pull_request:
    types: [milestoned]

jobs:
    milestoned:
        runs-on: ubuntu-latest
        steps:
        - name: Update milestone on PRs targeting this version
          uses: actions/github-script@v7
          with:
            script: |
              let milestone = '${{ github.event.pull_request.milestone.title }}'.slice(0, -1) + "0"
              let current_qa_versions = await github.rest.issues.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: "release-automation"
              })
              console.log(current_qa_versions)