name: Milestoned

on:
  pull_request:
    types: [milestoned]

jobs:
    milestoned:
        runs-on: ubuntu-latest
        steps:
        - name: Update milestone on PRs targeting this version
          uses: actions/github-script@v7
          with:
            script: |
              let milestone = '${{ github.event.pull_request.milestone.title }}'.slice(0, -1) + "0"
              let release_issues = await github.rest.issues.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: "release-automation"
              })
              console.log(release_issues)
              let release_issues_version = release_issues.data.map ((release_issue) => {
                return release_issue.title.match(release_issue_regex)
              })
              console.log(release_issues_version)
