name: Milestoned

on:
  pull_request:
    types: [milestoned]

jobs:
    milestoned:
        runs-on: ubuntu-latest
        steps:
        - name: Update milestone on PRs targeting this version
          uses: actions/github-script@v7
          with:
            script: |
              console.log("asu")
