name: Milestoned

on:
  pull_request:
    types: [milestoned]

jobs:
    milestoned:
        runs-on: ubuntu-latest
        steps:
        - name: Update milestone on PRs targeting this version
          uses: actions/github-script@v7
          with:
            script: |
              let milestone = '${{ github.event.issue.milestone.title }}'
              console.log(milestone)

              milestone = milestone.slice(0, -1) + "0"
              console.log(milestone)

              let current_qa_versions = github.rest.issues.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: "release-automation"
              })
              console.log(current_qa_versions)

              if (current_qa_versions.includes(base_version)) {
                echo "Milestone is set to the QA versions"
              } else {
                echo "Milestone is set to non QA versions!"
              }
